name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Обновление каждую полночь
  workflow_dispatch: # Позволяет запустить вручную
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: S-NOWNUM-B
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Настройки языков (включая организации)
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          repositories_affiliations: owner, collaborator, organization_member # Учитывает организации
          
          # Настройки внешнего вида (под ваш стиль)
          config_timezone: Europe/Moscow
          config_order: base.header, languages, base.activity
