name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: S-NOWNUM-B
          template: classic
          
          # 1. Оставляем всю информацию, но убираем подвал (удален блок metadata)
          base: header, activity, community, repositories
          
          # 2. Полная статистика по языкам (байты + проценты)
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          repositories_affiliations: owner, collaborator, organization_member
          
          # 3. Стилизация под твою карточку Streak
          config_timezone: Europe/Moscow
          config_colors: |
            {
              "canvas_default": "#0d1117",
              "fg_default": "#ffffff",
              "fg_muted": "#8b949e",
              "border_default": "rgba(0,0,0,0)"
            }
